<?php
/**
 * Created by PhpStorm.
 * User: doria
 * Date: 02/04/2018
 * Time: 11:59
 */

namespace App\Bundle\Factures;


use App\Bundle\Auth\Model\Connexion;
use App\Bundle\Bundle;
use App\Bundle\Database\Table\UsersTable;
use App\Bundle\Factures\Controller\Factures;
use Framework\Router;
use Framework\Router\RouteScope;
use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;

class FacturesBundle extends Bundle
{
    /**
     * @var UsersTable
     */
    protected $usersTable;

    /**
     * @var Connexion
     */
    protected $connexionmodel;

    /**
     * @var int
     */
    protected $usersId;

    public function initialize(ServerRequestInterface $request, ContainerInterface $container)
    {
        parent::initialize($request, $container); // TODO: Change the autogenerated stub
        $this->usersTable = $this->table->load(UsersTable::class);
        $this->renderer->make([
            "users" => $this->usersTable->find($this->session->get(Connexion::ID_SESSION))
        ]);
        $this->renderer->setLayout("Membre");
        $this->usersId = $this->session->get(Connexion::ID_SESSION);
    }
    public static function routes(Router $router): void
    {
        parent::routes($router);
        $router->scope("facture", function(RouteScope $routes){
            $routes->get("gestion-:slug", [Factures::class, "gestionFacture"], "facture.generer")->width("slug", "[0-9]+");
        });
    }
}