<?php
/**
 * Created by PhpStorm.
 * User: dorian
 * Date: 01/12/17
 * Time: 12:09
 */

namespace App\Bundle\Pages;


use App\Bundle\Bundle;
use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;

class PagesBundle extends Bundle
{
    public function initialize(ServerRequestInterface $request, ContainerInterface $container)
    {
        parent::initialize($request, $container); // TODO: Change the autogenerated stub
    }
}