<?php
/**
 * Created by PhpStorm.
 * User: doria
 * Date: 02/04/2018
 * Time: 12:00
 */

namespace App\Bundle\Factures\Controller;


use App\Bundle\Factures\FacturesBundle;
use App\Bundle\Factures\Model\FactureModel;
use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;

class Factures extends FacturesBundle
{

    /**
     * @var FactureModel
     */
    private $factureModel;

    public function initialize(ServerRequestInterface $request, ContainerInterface $container)
    {
        parent::initialize($request, $container); // TODO: Change the autogenerated stub
        $this->factureModel = $this->container->get(FactureModel::class);
    }


    public function gestionFacture(string $slug)
    {
        if($this->factureModel->devisExiste($this->usersId, $slug)){

            return $this->renderer->render("Gestion");
        }
    }

}