<?php
/**
 * Created by PhpStorm.
 * User: doria
 * Date: 12/12/2017
 * Time: 12:15
 */

namespace App\Bundle\Membres\Controller;


use App\Bundle\Membres\MembresBundle;
use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;
use App\Bundle\Membres\Model\Informations as InformationModel;

class Informations extends MembresBundle
{
    /**
     * @var InformationModel
     */
    private $informationModel;

    public function initialize(ServerRequestInterface $request, ContainerInterface $container)
    {
        parent::initialize($request, $container); // TODO: Change the autogenerated stub
        $this->informationModel = $container->get(InformationModel::class);
    }

    public function setInformationsEntreprise()
    {
        $validator = $this->getValidator();
        $validator->phoneNumber("phone")
            ->mail("mail")
            ->siret("siret")
            ->notEmpty("compagny_name")
            ->required("compagny_name");
        if ($validator->isValid()) {
            if($this->informationModel->setInformationsEntreprise($this->usersId, $this->parsedBody)){
                $this->flash->success("Informations mises à jour avec succès !");
            } else {
                $this->flash->error("Informations non mises à jour");
            }
        } else {
            $this->flash->error("Veuillez compléter correctement le formulaire");
        }
        return $this->redirect("membre.home");
    }

    public function setInformations()
    {
        $validator = $this->getValidator();
        $validator->required("first_name", "last_name", "city")
            ->dateTime("birthday")
            ->codePostal("cp");
        if ($validator->isValid()) {
            if ($this->informationModel->setInformations($this->usersId, $this->parsedBody)) {
                $this->flash->success("Informations mises à jour avec succès");

            } else {
                $this->flash->error("Les informations n'ont pas été mises à jour");
            }
        } else {
            $this->flash->error("Veuillez compléter correctement le formulaire");
        }
        return $this->redirect("membre.home");
    }
}