<?php
/**
 * Created by PhpStorm.
 * User: doria
 * Date: 13/02/2018
 * Time: 14:32
 */

namespace App\Bundle\Parametres;

use App\Bundle\Auth\Controller\Totp;
use App\Bundle\Auth\Model\Connexion;
use App\Bundle\Database\Table\UsersTable;
use App\Bundle\Parametres\Controller\Pages;
use App\Bundle\Parametres\Controller\PagesController;
use Framework\Router;
use Framework\Router\RouteScope;

class ParametresBundle extends \App\Bundle\Bundle
{
    /**
     * @var UsersTable
     */
    private $usersTable;
    protected $usersId;

    public function initialize(\Psr\Http\Message\ServerRequestInterface $request, \Psr\Container\ContainerInterface $container)
    {
        parent::initialize($request, $container); // TODO: Change the autogenerated stub
        $this->renderer->setLayout("Membre");
        $this->usersTable = $this->table->load(UsersTable::class);
        $this->renderer->make([
            "users" => $this->usersTable->find($this->session->get(Connexion::ID_SESSION))
        ]);
        $this->usersId = $this->session->get(Connexion::ID_SESSION);
    }


    public static function routes(Router $router): void
    {
        $router->scope("/parametres/", function (RouteScope $routes){
            $routes->get("/", [Pages::class, "index"], "params.show");
            $routes->post("get-qr-code", [Pages::class, "getTotpQrCode"], "code");
            $routes->get("activation-authentification-a-deux-facteurs", [Totp::class, "activer"], "otp.active");
            $routes->post("desactivation-authentification-a-deux-facteurs", [Totp::class, "desactiver"], "otp.desactive");
            $routes->post("activation-otp", [Totp::class, "activer"], "otp.active.send");
        });
    }

}
