<?php
/**
 * Created by PhpStorm.
 * User: doria
 * Date: 04/01/2018
 * Time: 14:53
 */

namespace App\Bundle\Ressources\Controller;


use App\Bundle\Ressources\RessourcesBundle;
use Framework\Exception\FileReaderRessourceException;
use GuzzleHttp\Psr7\Response;
use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;

class FileReader extends RessourcesBundle
{

    private $cssPath;

    public function initialize(ServerRequestInterface $request, ContainerInterface $container)
    {
        parent::initialize($request, $container); // TODO: Change the autogenerated stub
        $this->cssPath=ROOT."public".DS."css".DS;
    }

    public function cssLocal(string $file)
    {
        $fileName=$this->cssPath.$file;
        if(is_file($fileName)){
            $content=file_get_contents($fileName);
            return new Response(200, ["Content-type"=>"text/css"], $content);
        }
        throw new FileReaderRessourceException();
    }
}